---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: '{{ template "ocs-monkey-generator.fullname" . }}'

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: '{{ template "ocs-monkey-generator.fullname" . }}'
subjects:
  - kind: ServiceAccount
    name: '{{ template "ocs-monkey-generator.fullname" . }}'
    namespace: "{{ .Release.Namespace }}"
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
